# Generated by Django 4.2.16 on 2024-10-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
