# Generated by Django 5.1.2 on 2024-11-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingrib', '0002_user_age_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
